In [1]:
import pandas as pd
import numpy as np
from pandas import read_excel
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import chi2
from sklearn import preprocessing
# code obtained from https://scikit-learn.org/stable/modules/feature_selection.html#

In [2]:
f = open("C:\\Users\\jinhan laptop\\Desktop\\FIT\\FIT3162\\Assignment\\Data_Files\\columnNamesUCI.txt", "r")
file_str = f.read()
f.close()

names = file_str.split("\n")
print(names)

['id', 'ccf', 'age', 'sex', 'painloc', 'painexer', 'relrest', 'pncaden', 'cp', 'trestbps', 'htn', 'chol', 'smoke', 'cigs', 'years', 'fbs', 'dm', 'famhist', 'restecg', 'ekgmo', 'ekgday', 'ekgyr', 'dig', 'prop', 'nitr', 'pro', 'diuretic', 'proto', 'thaldur', 'thaltime', 'met', 'thalach', 'thalrest', 'tpeakbps', 'tpeakbpd', 'dummy', 'trestbpd', 'exang', 'xhypo', 'oldpeak', 'slope', 'rldv5', 'rldv5e', 'ca', 'restckm', 'exerckm', 'restef', 'restwm', 'exeref', 'exerwm', 'thal', 'thalsev', 'thalpul', 'earlobe', 'cmo', 'cday', 'cyr', 'num', 'lmt', 'ladprox', 'laddist', 'diag', 'cxmain', 'ramus', 'om1', 'om2', 'rcaprox', 'rcadist', 'lvx1', 'lvx2', 'lvx3', 'lvx4', 'lvf', 'cathef', 'junk']


In [37]:
# fname = "C:\\Users\\jinhan laptop\\Desktop\\FIT\\FIT3162\\Assignment\\Data_Files\\updated_hungarian.xlsx"
fname = "C:\\Users\\jinhan laptop\\Desktop\\FIT\\FIT3162\\Assignment\\Data_Files\\updated_cleveland.data.xlsx"
dataframe = read_excel(fname, header = None, names=names)
print(dataframe)
print(dataframe.num)

      id  ccf  age  sex  painloc  painexer  relrest  pncaden  cp  trestbps  \
0      1    0   63    1       -9        -9       -9       -9   1       145   
1      2    0   67    1       -9        -9       -9       -9   4       160   
2      3    0   67    1       -9        -9       -9       -9   4       120   
3      4    0   37    1       -9        -9       -9       -9   3       130   
4      6    0   41    0       -9        -9       -9       -9   2       130   
5      7    0   56    1       -9        -9       -9       -9   2       120   
6      8    0   62    0       -9        -9       -9       -9   4       140   
7      9    0   57    0       -9        -9       -9       -9   4       120   
8     10    0   63    1       -9        -9       -9       -9   4       130   
9     11    0   53    1       -9        -9       -9       -9   4       140   
10    12    0   57    1       -9        -9       -9       -9   4       140   
11    13    0   56    0       -9        -9       -9       -9   2

In [38]:

for i in range(dataframe.shape[0]): # for each row
    for column in dataframe.columns:
        if dataframe.at[i, column] == -9:
            dataframe.loc[i, column] = np.nan
print(dataframe)

      id  ccf  age  sex  painloc  painexer  relrest  pncaden  cp  trestbps  \
0      1    0   63    1      NaN       NaN      NaN      NaN   1       145   
1      2    0   67    1      NaN       NaN      NaN      NaN   4       160   
2      3    0   67    1      NaN       NaN      NaN      NaN   4       120   
3      4    0   37    1      NaN       NaN      NaN      NaN   3       130   
4      6    0   41    0      NaN       NaN      NaN      NaN   2       130   
5      7    0   56    1      NaN       NaN      NaN      NaN   2       120   
6      8    0   62    0      NaN       NaN      NaN      NaN   4       140   
7      9    0   57    0      NaN       NaN      NaN      NaN   4       120   
8     10    0   63    1      NaN       NaN      NaN      NaN   4       130   
9     11    0   53    1      NaN       NaN      NaN      NaN   4       140   
10    12    0   57    1      NaN       NaN      NaN      NaN   4       140   
11    13    0   56    0      NaN       NaN      NaN      NaN   2

In [39]:
df = dataframe.fillna(dataframe.mean())
print(df)
print(df.num) # target

      id  ccf  age  sex  painloc  painexer  relrest  pncaden  cp  trestbps  \
0      1    0   63    1      NaN       NaN      NaN      NaN   1       145   
1      2    0   67    1      NaN       NaN      NaN      NaN   4       160   
2      3    0   67    1      NaN       NaN      NaN      NaN   4       120   
3      4    0   37    1      NaN       NaN      NaN      NaN   3       130   
4      6    0   41    0      NaN       NaN      NaN      NaN   2       130   
5      7    0   56    1      NaN       NaN      NaN      NaN   2       120   
6      8    0   62    0      NaN       NaN      NaN      NaN   4       140   
7      9    0   57    0      NaN       NaN      NaN      NaN   4       120   
8     10    0   63    1      NaN       NaN      NaN      NaN   4       130   
9     11    0   53    1      NaN       NaN      NaN      NaN   4       140   
10    12    0   57    1      NaN       NaN      NaN      NaN   4       140   
11    13    0   56    0      NaN       NaN      NaN      NaN   2

In [40]:
# print(df.isna())
# print(df.num.isna())
# print
df = df.dropna(axis=1,how='all')
print(df)
print(df.num)

      id  ccf  age  sex  cp  trestbps  htn  chol       cigs      years ...   \
0      1    0   63    1   1       145    1   233  50.000000  20.000000 ...    
1      2    0   67    1   4       160    1   286  40.000000  40.000000 ...    
2      3    0   67    1   4       120    1   229  20.000000  35.000000 ...    
3      4    0   37    1   3       130    0   250   0.000000   0.000000 ...    
4      6    0   41    0   2       130    1   204   0.000000   0.000000 ...    
5      7    0   56    1   2       120    1   236  20.000000  20.000000 ...    
6      8    0   62    0   4       140    0   268   0.000000   0.000000 ...    
7      9    0   57    0   4       120    1   354   0.000000   0.000000 ...    
8     10    0   63    1   4       130    1   254   0.000000   0.000000 ...    
9     11    0   53    1   4       140    0   203  20.000000  25.000000 ...    
10    12    0   57    1   4       140    0   192  75.000000  25.000000 ...    
11    13    0   56    0   2       140    0   294   0

In [41]:
# normalize data
x = df.values #returns a numpy array
# columns = df.columns
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled, columns = df.columns)
print(df)
print(df.num)

           id  ccf       age  sex        cp  trestbps  htn      chol  \
0    0.000000  0.0  0.708333  1.0  0.000000  0.481132  1.0  0.244292   
1    0.003367  0.0  0.791667  1.0  1.000000  0.622642  1.0  0.365297   
2    0.006734  0.0  0.791667  1.0  1.000000  0.245283  1.0  0.235160   
3    0.010101  0.0  0.166667  1.0  0.666667  0.339623  0.0  0.283105   
4    0.016835  0.0  0.250000  0.0  0.333333  0.339623  1.0  0.178082   
5    0.020202  0.0  0.562500  1.0  0.333333  0.245283  1.0  0.251142   
6    0.023569  0.0  0.687500  0.0  1.000000  0.433962  0.0  0.324201   
7    0.026936  0.0  0.583333  0.0  1.000000  0.245283  1.0  0.520548   
8    0.030303  0.0  0.708333  1.0  1.000000  0.339623  1.0  0.292237   
9    0.033670  0.0  0.500000  1.0  1.000000  0.433962  0.0  0.175799   
10   0.037037  0.0  0.583333  1.0  1.000000  0.433962  0.0  0.150685   
11   0.040404  0.0  0.562500  0.0  0.333333  0.433962  0.0  0.383562   
12   0.043771  0.0  0.562500  1.0  0.666667  0.339623  0.0  0.29

In [42]:
# df_vals = dataframe.values
df_no_target = df[df.columns.difference(["num"])]
print(df_no_target) # setting target and non target
df_vals = df_no_target.values
print(df.num.values)
target_vals = df.num.values

          age        ca  ccf      cday      chol      cigs       cmo  \
0    0.708333  0.000000  0.0  0.500000  0.244292  0.505051  0.090909   
1    0.791667  1.000000  0.0  0.133333  0.365297  0.404040  0.090909   
2    0.791667  0.666667  0.0  0.633333  0.235160  0.202020  0.090909   
3    0.166667  0.000000  0.0  0.100000  0.283105  0.000000  0.090909   
4    0.250000  0.000000  0.0  0.566667  0.178082  0.000000  0.090909   
5    0.562500  0.000000  0.0  0.300000  0.251142  0.202020  0.181818   
6    0.687500  0.666667  0.0  0.033333  0.324201  0.000000  0.090909   
7    0.583333  0.000000  0.0  0.666667  0.520548  0.000000  0.545455   
8    0.708333  0.333333  0.0  0.066667  0.292237  0.000000  0.545455   
9    0.500000  0.000000  0.0  0.166667  0.175799  0.202020  0.545455   
10   0.583333  0.000000  0.0  0.000000  0.150685  0.757576  0.545455   
11   0.562500  0.000000  0.0  0.600000  0.383562  0.000000  0.000000   
12   0.562500  0.333333  0.0  0.633333  0.296804  0.303030  0.00

In [43]:
features = SelectKBest(f_classif, k=5).fit_transform(df_vals, dataframe.num)
print(features)

[[0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


C:\Users\jinhan laptop\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:114: UserWarning: Features [ 2 12 24 26 27 36] are constant.
  UserWarning)
C:\Users\jinhan laptop\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:115: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
C:\Users\jinhan laptop\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [44]:
selector = SelectKBest(f_classif, k = 14) #chi2, ...  # use some other algorithms to find the most informative features. best first search 
selector.fit_transform(df_no_target, target_vals)
features = selector.get_support(indices = True)
print(features)
for x in features:
    print(x)
print(df_no_target.columns[features])
features = [column for column in df_no_target.columns[features]]
selector.columns = features

print(df_no_target[selector.columns])

print(selector.columns)
#     #Select Model
#     selector = VarianceThreshold(0) #Defaults to 0.0, e.g. only remove features with the same value in all samples

#     #Fit the Model
#     selector.fit(data)
#     features = selector.get_support(indices = True) #returns an array of integers corresponding to nonremoved features
#     features = [column for column in data[features]] #Array of all nonremoved features' names

#     #Format and Return
#     selector = pd.DataFrame(selector.transform(data))
#     selector.columns = features
# print(df_no_target)

[ 1  7  8 17 22 23 24 32 33 37 38 42 43 44]
1
7
8
17
22
23
24
32
33
37
38
42
43
44
Index(['ca', 'cp', 'cxmain', 'exang', 'laddist', 'ladprox', 'lmt', 'oldpeak',
       'om1', 'rcadist', 'rcaprox', 'slope', 'thal', 'thalach'],
      dtype='object')
           ca        cp  cxmain  exang  laddist  ladprox  lmt   oldpeak  om1  \
0    0.000000  0.000000     0.0    0.0      0.0      0.0  0.0  0.370968  0.0   
1    1.000000  1.000000     1.0    1.0      1.0      1.0  0.0  0.241935  0.0   
2    0.666667  1.000000     0.0    1.0      0.0      0.0  0.0  0.419355  0.0   
3    0.000000  0.666667     0.0    0.0      0.0      0.0  0.0  0.564516  0.0   
4    0.000000  0.333333     0.0    0.0      0.0      0.0  0.0  0.225806  0.0   
5    0.000000  0.333333     0.0    0.0      0.0      0.0  0.0  0.129032  0.0   
6    0.666667  1.000000     0.0    0.0      0.0      1.0  0.0  0.580645  1.0   
7    0.000000  1.000000     0.0    1.0      0.0      0.0  0.0  0.096774  0.0   
8    0.333333  1.000000     0.0 

C:\Users\jinhan laptop\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:114: UserWarning: Features [ 2 12 24 26 27 36] are constant.
  UserWarning)
C:\Users\jinhan laptop\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:115: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
C:\Users\jinhan laptop\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [ ]:
test = SelectKBest(f_classif, k=5)
# fit = test.fit(df_vals, target_vals)
newX = test.fit_transform(df_no_target, target_vals)
print(newX.shape)
print(newX)
# set_printoptions(precision=3)
print(fit.scores_)
features2=fit.transform(df_vals)
print(features2)
# print(features2[0:5,:])
# print(df_no_target[df_no_target.columns[30]])

In [ ]:
print(features2)

In [ ]:
print(df_no_target['thaltime'])

In [ ]:
print(dataframe.columns[31])
print(df_no_target.shape)

In [ ]:
file_str.split("name")

In [ ]:
file_str_newline_removed = file_str.replace("\n"," ")
print(file_str_newline_removed)

In [ ]:
file_str_replaced_name_with_new_line = file_str_newline_removed.replace("name ", "\n")
print(file_str_replaced_name_with_new_line)

In [ ]:
f = open("updated_cleveland.data", "w")

answer = file_str_replaced_name_with_new_line
f.write(answer)
f.close()